permalink: /:year/:month/:day/:title 

pygments: true

title : Nicholas Gunner
tagline: Multimedia Storyteller
author : 
  name : Nicholas Gunner
  email : gunnernr@gmail.com
  github : ngunner
  twitter : nicholas_gunner
  web : http://www.nicholasgunner.com

production_url : http://www.nicholasgunner.com

version : 0.3.0

baseurl : http://ngunner.github.io/

 
comments :
  provider : disqus
  disqus :
    short_name : 
   
        
analytics :
  google : 
    tracking_id : 'UA-48524948-1'


authors:
  ngunner:
    name: Nicholas Gunner
    display_name: Nicholas Gunner
    bio: New Media Manager at SUNY Fredonia. Multimedia Storyteller.
    gravatar: http://www.gravatar.com/avatar/a85d870dce3cc177b6b0016a1ef4c200.png
    email: gunnernr@gmail.com
    web: http://www.nicholasgunner.com
    twitter: nicholas_gunner
    github: ngunner
   
  
timezone : America/New_York


prose:
  rooturl: '_posts'
  siteurl: 'http://www.nicholasgunner.com'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "published"
        field:
          element: "checkbox"
          label: "Published?"
          value: "true"
      - name: "title"
        field:
          element: "text"
          label: "Post title"
      - name: "description"
        field:
          element: "text"
          label: "Post summary"
      - name: "categories"
        field:
          element: "multiselect"
          label: "Categories"
          options:
            - name: "Video"
              value: "video"
            - name: "Content Design"
              value: "content"
      - name: "author"
        field:
          element: "multiselect"
          label: "Author"
          options:
            - name: "Nicholas Gunner"
              value: "ngunner"
      - name: "image"
        field:
          element: "text"
          label: "URL to a featured image"