permalink: /:year/:month/:day/:title 

highlighter: pygments
markdown: kramdown

title : Nicholas Gunner
tagline: Digital Storyteller
author :
  name : Nicholas Gunner
  email : gunnernr@gmail.com
  github : ngunner
  twitter : ngunner

production_url : http://ngunner.github.io/

version : 0.1.0

baseurl : http://nicholasgunner.com

timezone : America/New_York
